INSERT INTO b_pedidos (nombre,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('Auriculares TWS Pro60 con Bluetooth, color negro','Auriculares TWS Pro60 con Bluetooth, color negro',1,37.82,90,52.18,'S','S',2,'2024-08-19','');
INSERT INTO b_pedidos (nombre,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('Auriculares TWS Pro60 con Bluetooth, color negro','Auriculares TWS Pro60 con Bluetooth, color negro',1,37.82,90,52.18,'S','S',2,'2024-08-19','');
INSERT INTO b_pedidos (nombre,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('Auriculares inalámbricos X15 TWS para juegos, color negro','Auriculares inalámbricos X15 TWS para juegos, color negro',1,34.01,100,65.99,'S','S',2,'2024-08-19','');

INSERT INTO b_pedidos (nombre,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('Auriculares inalámbricos X15 TWS para juegos, color negro','Auriculares inalámbricos X15 TWS para juegos, color negro',1,34.01,100,65.99,'S','S',2,'2024-08-19','');
INSERT INTO b_pedidos (nombre,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('Auriculares inalámbricos M10 TWS, cascos con Bluetooth, color negro','Auriculares inalámbricos M10 TWS, cascos con Bluetooth, color negro',1,49.21,100,50.79,'S','S',2,'2024-08-19','');
INSERT INTO b_pedidos (nombre,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('Auriculares inalámbricos M10 TWS, cascos con Bluetooth, color negro','Auriculares inalámbricos M10 TWS, cascos con Bluetooth, color negro',1,49.21,120,70.79,'S','S',2,'2024-08-19','');

INSERT INTO b_pedidos (nombre,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('Enchufe Wifi inteligente con Control remoto para el hogar','Enchufe Wifi inteligente con Control remoto para el hogar',1,37.8,100,0,'N','S',2,'2024-08-19','');
INSERT INTO b_pedidos (nombre,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('Enchufe Wifi inteligente con Control remoto para el hogar','Enchufe Wifi inteligente con Control remoto para el hogar',1,37.8,100,0,'N','S',2,'2024-08-19','');
INSERT INTO b_pedidos (nombre,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('G11 auriculares inalámbricos con Bluetooth para videojuegos, color negro','G11 auriculares inalámbricos con Bluetooth para videojuegos, color negro',1,34.02,100,65.98,'S','S',2,'2024-08-19','');

INSERT INTO b_pedidos (nombre,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('G11 auriculares inalámbricos con Bluetooth para videojuegos, color negro','G11 auriculares inalámbricos con Bluetooth para videojuegos, color negro',1,34.02,100,65.98,'S','S',2,'2024-08-19','');
INSERT INTO b_pedidos (nombre,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('ONENUO-Sensor de puerta y ventana con WiFi, color blanco','ONENUO-Sensor de puerta y ventana con WiFi, color blanco',1,41.61,80,0,'N','S',2,'2024-08-19','');
INSERT INTO b_pedidos (nombre,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('ONENUO-Sensor de puerta y ventana con WiFi, color blanco','ONENUO-Sensor de puerta y ventana con WiFi, color blanco',1,41.61,80,0,'N','S',2,'2024-08-19','');

INSERT INTO b_pedidos (nombre,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('Bombilla inteligente E27 con WiFi, luz LED regulable con Control de voz','Bombilla inteligente E27 con WiFi, luz LED regulable con Control de voz',1,41.61,100,0,'N','S',2,'2024-08-19','');
INSERT INTO b_pedidos (nombre,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('Bombilla inteligente E27 con WiFi, luz LED regulable con Control de voz','Bombilla inteligente E27 con WiFi, luz LED regulable con Control de voz',1,41.61,100,0,'N','S',2,'2024-08-19','');
INSERT INTO b_pedidos (nombre,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('M90-auriculares inalámbricos TWS con Bluetooth, color negro','M90-auriculares inalámbricos TWS con Bluetooth, color negro',1,41.6,120,78.4,'S','S',2,'2024-08-19','');

INSERT INTO b_pedidos (nombre,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('M90-auriculares inalámbricos TWS con Bluetooth, color negro','M90-auriculares inalámbricos TWS con Bluetooth, color negro',1,41.6,100,58.4,'S','S',2,'2024-08-19','');
INSERT INTO b_pedidos (nombre,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('Auriculares T8 Tws con Bluetooth 5,3, color morado','Auriculares T8 Tws con Bluetooth 5,3, color morado',1,51.11,110,58.89,'S','S',2,'2024-08-19','');
INSERT INTO b_pedidos (nombre,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('Reloj inteligente T166X para hombre y mujer, pulsera deportiva, color negro','Reloj inteligente T166X para hombre y mujer, pulsera deportiva, color negro',1,75.81,150,0,'P','S',2,'2024-08-19','');

INSERT INTO b_pedidos (nombre,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('Reloj inteligente T166X para hombre y mujer, pulsera deportiva, color negro','Reloj inteligente T166X para hombre y mujer, pulsera deportiva, color negro',1,75.81,150,74.19,'S','S',2,'2024-08-19','');
INSERT INTO b_pedidos (nombre,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('Reloj inteligente T166X para hombre y mujer, pulsera deportiva, color rosa','Reloj inteligente T166X para hombre y mujer, pulsera deportiva, color rosa',1,75.81,150,74.19,'S','S',2,'2024-08-19','');