INSERT INTO b_pedidos (producto,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('Transmisor FM compatible con tarjeta TF','Transmisor FM compatible con tarjeta TF, reproductor MP3 de disco U para coche',1,35.89,0,0,'N','S',4,'2024-10-01','');
INSERT INTO b_pedidos (producto,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('Reloj inteligente T166X - negro','Reloj inteligente T166X para hombre y mujer, pulsera deportiva con pantalla táctil completa - negro',1,71.98,120,48.02,'S','S',4,'2024-10-01','');
INSERT INTO b_pedidos (producto,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('Reloj inteligente T166X - negro','Reloj inteligente T166X para hombre y mujer, pulsera deportiva con pantalla táctil completa - negro',1,71.98,0,0,'N','S',4,'2024-10-01','');
INSERT INTO b_pedidos (producto,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('Reloj inteligente T166X - negro','Reloj inteligente T166X para hombre y mujer, pulsera deportiva con pantalla táctil completa - negro',1,71.98,0,0,'N','S',4,'2024-10-01','');
INSERT INTO b_pedidos (producto,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('Reloj inteligente T166X - rosa','Reloj inteligente T166X para hombre y mujer, pulsera deportiva con pantalla táctil completa - rosa',1,71.98,120,48.02,'S','S',4,'2024-10-01','');

INSERT INTO b_pedidos (producto,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('Reloj inteligente T166X - rosa','Reloj inteligente T166X para hombre y mujer, pulsera deportiva con pantalla táctil completa - rosa',1,71.98,0,0,'N','S',4,'2024-10-01','');
INSERT INTO b_pedidos (producto,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('Reloj inteligente T166X - rosa','Reloj inteligente T166X para hombre y mujer, pulsera deportiva con pantalla táctil completa - rosa',1,71.98,0,0,'N','S',4,'2024-10-01','');
INSERT INTO b_pedidos (producto,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('Reloj inteligente T166X - gris','Reloj inteligente T166X para hombre y mujer, pulsera deportiva con pantalla táctil completa - gris',1,71.98,120,48.02,'S','S',4,'2024-10-01','');
INSERT INTO b_pedidos (producto,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('Reloj inteligente T166X - gris','Reloj inteligente T166X para hombre y mujer, pulsera deportiva con pantalla táctil completa - gris',1,71.98,0,0,'P','N',4,'2024-10-01','');

INSERT INTO b_pedidos (producto,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('Cargador de coche de 6 puertos','Cargador de coche de 6 puertos de 100W, carga rápida PD QC3.0 USB C',1,31.88,0,0,'N','S',4,'2024-10-01','');
INSERT INTO b_pedidos (producto,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('Auriculares Y80','Auriculares inalámbricos Y80 con Bluetooth 5,1,',1,43.91,80,36.09,'S','S',4,'2024-10-01','');
INSERT INTO b_pedidos (producto,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('Auriculares TWS M90','Auriculares inalámbricos TWS M90 originales',1,39.9,0,0,'P','N',4,'2024-10-01','');
INSERT INTO b_pedidos (producto,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('Auriculares TWS M90','Auriculares inalámbricos TWS M90 originales',1,39.9,80,40.1,'S','S',4,'2024-10-01','');
INSERT INTO b_pedidos (producto,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('Auriculares TWS F9-5','Auriculares TWS F9-5, inalámbricos por Bluetooth',1,31.88,50,18.12,'S','S',4,'2024-10-01','');

INSERT INTO b_pedidos (producto,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('Auriculares TWS F9-5','Auriculares TWS F9-5, inalámbricos por Bluetooth',1,31.88,0,0,'P','N',4,'2024-10-01','');
INSERT INTO b_pedidos (producto,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('M51 coche Bluetooth MP3','M51 coche Bluetooth MP3 coche multifunción USB',1,41.9,0,0,'P','N',4,'2024-10-01','');
INSERT INTO b_pedidos (producto,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('Reproductor de Mp3 para coche','Reproductor de Mp3 para coche, Cargador rápido Usb Dual, receptor Fm Bluetooth',1,31.88,0,0,'N','S',4,'2024-10-01','');
INSERT INTO b_pedidos (producto,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('Auriculares X15 Pro','Auriculares inalámbricos X15 Pro black',1,35.89,80,0,'N','S',4,'2024-10-01','');
INSERT INTO b_pedidos (producto,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('Auriculares X15 TWS','Auriculares inalámbricos X15 TWS para juegos, color negro',1,35.89,80,0,'N','S',4,'2024-10-01','');
INSERT INTO b_pedidos (producto,descripcion,cantidad,precio_costo,precio_venta,ganancia,estatus_venta,estatus_envio,id_pedido,fecha_registro,imagen) VALUES('Auriculares S20','Auriculares inalámbricos S20 con Bluetooth 5,3',1,53.93,100,46.07,'S','S',4,'2024-10-01','');
